services:
  db:
    image: postgres
    #    restart: alway
    environment:
      - POSTGRES_PASSWORD=123123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
