[package]
name = "erp_backend"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "./migration/src/lib.rs",
]

[[bin]]
name = "app"
path = "src/bin/main.rs"

# [[bin]]
# name = "administration gRPC server"
# path = "src/bin/administration.rs"

# [[bin]]
# name = "traffic gRPC server"
# path = "src/bin/traffic.rs"

# [[bin]]
# name = "migrations"
# path = "./migration"

[features]
multitenancy_fallback = []

[dependencies]
migration = { path = "./migration" }

# --- ğŸŒ Web Framework & Routing ---
axum = "0.8.3"

axum-extra = { version = "0.10.1", features = ["query", "typed-header", "multipart"] }
tokio = { version = "1.42.0", features = ["full"] }
tungstenite = "0.28.0"
tokio-tungstenite = { version = "0.28.0", features = ["native-tls"] }
tower = { version = "0.5.2", features = ["full"] }
tower-http = { version = "0.6.2", features = ["compression-full", "cors", "full"] }

# --- ğŸ“˜ OpenAPI / Swagger UI ---
utoipa = { version = "5.2.0", features = ["axum_extras", "uuid", "chrono"] }
utoipa-axum = "0.2.0"
utoipa-swagger-ui = { version = "9.0.0", features = ["axum"] }

# --- ğŸ›¡ï¸ Auth, Security ---
argon2 = "0.5.3"
jsonwebtoken = "9.3.0"
validator = { version = "0.20.0", features = ["derive"] }

# --- ğŸ—„ï¸ Database / ORM ---
sqlx = { version = "=0.6.3", features = ["runtime-tokio-rustls", "postgres"] }
sea-orm = { version = "2.0.0-rc.19", features = ["sqlx-postgres", "runtime-tokio-rustls", "debug-print", "macros"] }
sea-orm-migration = { version = "=1.1.10", features = ["default"] }

# --- ğŸ§  Redis Clients ---
redis = { version = "0.27.6", features = ["tokio-comp"] }
fred = { version = "7.1.2", features = ["metrics", "partial-tracing"] }

# --- ğŸ§° Utilities, Errors, Traits ---
anyhow = "1.0.94"
async-trait = "0.1.83"
config = "0.15.0"
error-stack = "0.4.1"
thiserror = "1.0.69"
once_cell = "1.21.1"
uuid = "1.11.0"
futures = "0.3.30"
bytes = "1.9.0"

# --- ğŸ“Š Logging / Tracing ---
log = "0.4.14"
env_logger = "0.11.7"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

# --- ğŸ§ª JSON, Serialize / Deserialize ---
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_urlencoded = "0.7.1"
serde_with = "3.12.0"

# --- ğŸ“… Time, Date, String tools ---
chrono = { version = "0.4.39", features = ["serde"] }
chrono-tz = "0.10.4"
strum = { version = "0.26.3", features = ["derive", "strum_macros"] }

# --- ğŸ“¦ CSV & Data Export ---
csv = "1.3.1"

measure_time = "0.9.0"
websocket = "0.27.1"

# --- ğŸŒ HTTP Client ---
reqwest = { version = "0.12.9", features = ["json"] }
rand = "0.8.5"
sea-query = "0.32.3"
regex = "1.11.1"

rdkafka = "0.38.0"

# --- ğŸ§ª gRPC ---
prost = "0.11.3"
tonic = "0.13.1"
itertools = "0.13.0"

[build-dependencies]
tonic-build = "0.13.1"
